- AmcCarrierCore/core/AmcCarrierBsi.vhd
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/core/AmcCarrierSysReg.vhd
- AmcCarrierCore/dcp/Makefile
- AmcCarrierCore/dcp/hdl/AmcCarrierEth.vhd
- AmcCarrierCore/dcp/images/AmcCarrierCore.dcp
- AppHardware/RtmCryoDet/rtl/RtmCryoDet.vhd
- AppHardware/RtmCryoDet/xdc/RtmCryoDet.xdc
- python/AmcCarrierCore/AmcCarrierCore.py
- python/AppHardware/RtmCryoDet/_spiMax.py
- python/AppTop/TopLevel.py
- python/DacSigGen/DacSigGen.py
- ruckus.tcl
1) Updating to surf v1.7.3 (RSSI bug fix)
2) Updating the cryo-det RTM firmware and python
3) Adding the ability to execute IPROG command by ETH (required for cryo-det)
4) Misc. python scripts updates and polishing
> v2.3.1 release candidate

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/dcp/Makefile
- AmcCarrierCore/dcp/images/AmcCarrierCore.dcp
- AppHardware/RtmCryoDet/xdc/RtmCryoDet.xdc
- releaseNotes.py
- ruckus.tcl
Fixed AppTop connection outbound debug stream
> v2.3.2 release candidate

- AmcCarrierCore/core/AmcCarrierCoreBase.vhd
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/dcp/images/AmcCarrierCore.dcp
- ruckus.tcl
###Description
Updating to lcls-timing-core v1.11 (inlucdes Tpgministream bsa support)
> v2.3.3 release candidate

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/dcp/images/AmcCarrierCore.dcp
- AmcCarrierCore/ruckus.tcl
- AmcCarrierCore/vivado/promgen.tcl
- AppTop/ruckus.tcl
- python/AppTop/TopLevel.py
- ruckus.tcl
1) Updating the TPGMiniCore register mapping
2) CPSW YAML and Rogue python updates
3) updating KU+ part numbers to speed grade -2 
[ESLTIMING-16](https://jira.slac.stanford.edu/browse/ESLTIMING-16)
> v2.3.4 release candidate

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/dcp/Makefile
- AmcCarrierCore/dcp/images/AmcCarrierCore.dcp
- AppTop/rtl/AppMsgIb.vhd
- AppTop/rtl/AppMsgOb.vhd
- AxisBramRingBuffer/rtl/AxisBramFlashBuffer.vhd
- AxisBramRingBuffer/rtl/AxisBramFlashBufferRdFsm.vhd
- ruckus.tcl
1) Updating to timing v1.11.2
2) Added Added AXIS_TDATA_WIDTH_G generic to AppMsgIb.vhd
3) Added Added AXIS_TDATA_WIDTH_G generic to AppMsgOb.vhd
4) Added Added AXIS_TDATA_WIDTH_G generic to AxisBramFlashBuffer.vhd
> v2.4.1 release candidate

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/yaml/AmcCarrierCore.yaml
- ruckus.tcl
1) Allowing Vivado 2018.1
2) Revering back the device name to SwRssiServer[1:0]
> v2.4.2 release candidate

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AppHardware/RtmRfInterlock/yaml/RtmRfInterlock.yaml
CPSW YAML update for RtmRfInterlock.yaml
> v2.4.4 release candidate

- AppTop/rtl/xcku060/AppTop.vhd
- AppTop/rtl/xcku11p/AppTop.vhd
Adding missing JESD_USR_DIV_G to kcu060 and kcu11p
[ESLCOMMON-218](https://jira.slac.stanford.edu/browse/ESLCOMMON-218)
> Adding missing JESD_USR_DIV_G to kcu060 and kcu11p

- python/AppTop/AppTop.py
- python/AppTop/AppTopJesd.py
- python/AppTop/TopLevel.py
Add argument for creating the DRP device to the GTH
###JIRA 
[ESLCOMMON-217](https://jira.slac.stanford.edu/browse/ESLCOMMON-217)
> Add argument for creating the DRP device to the GTH

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/dcp/Makefile
- AmcCarrierCore/dcp/images/AmcCarrierCore.dcp
- AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxCore.vhd
- AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxDualCore.vhd
- AppHardware/RtmRfInterlock/core/RtmRfInterlockCore.vhd
- AppHardware/RtmRfInterlock/yaml/RtmRfInterlock.yaml
- AppHardware/common/rtl/JesdSyncIn.vhd
- AppHardware/common/rtl/JesdSyncOut.vhd
- AppTop/rtl/xcku040/AppTopJesd.vhd
- AppTop/rtl/xcku040/AppTopJesd204b.vhd
- AppTop/rtl/xcku040_mpsln/AppTopJesd.vhd
- AppTop/rtl/xcku040_mpsln/AppTopJesd204b.vhd
- AppTop/rtl/xcku060/AppTop.vhd
- AppTop/rtl/xcku060/AppTopJesd.vhd
- AppTop/rtl/xcku060/AppTopJesd204b.vhd
- AppTop/rtl/xcku11p/AppTop.vhd
- AppTop/rtl/xcku11p/AppTopJesd.vhd
- AppTop/rtl/xcku11p/AppTopJesd204b.vhd
- python/AppTop/AppTop.py
- python/AppTop/AppTopJesd.py
- python/AppTop/TopLevel.py
- ruckus.tcl
1) Added missing JESD_USR_DIV_G to kcu060 and kcu11p
2) Added argument for creating the DRP device to the GTH
3) Added the rxPowerDown and txPowerDown to JESD wrappers
4) bug fix for SURF v1.6 (or later), which is required for RF Interlock RTM
> v2.4.5 release candiate 

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/dcp/Makefile
- AmcCarrierCore/dcp/images/AmcCarrierCore.dcp
- AppHardware/common/rtl/JesdSyncIn.vhd
- AppHardware/common/rtl/JesdSyncOut.vhd
- DaqMuxV2/rtl/DaqMuxV2.vhd
- python/AppHardware/RtmCryoDet/_spiSr.py
- python/AppTop/AppTop.py
- python/AppTop/TopLevel.py
- python/DacSigGen/DacSigGen.py
- ruckus.tcl
1) Lots of rogue python updates
2) Bug fix for DepackerV2 (surf@v1.8.4)
3) Adding more pipelining to JESD wrappers to help meeting timing for cryo-det (307 MHz JESD clk)
4) removed includeStream from python/AppTop/TopLevel.py
> v2.4.6 release candidate

- python/AppTop/TopLevel.py
Connect PCIe TDEST 0x2 to streamVc1
> Connect PCIe TDEST 0x2 to streamVc1

- AppHardware/RtmCryoDet/rtl/RtmCryoDet.vhd
- AppHardware/RtmCryoDet/rtl/RtmCryoSpiMaster.vhd
- python/AppHardware/RtmCryoDet/_rtmCryoDet.py
- python/AppHardware/RtmCryoDet/_spiCryo.py
For the read command should it be 
write
read
or 2 sequential reads?
read
read
[cryostat_card_interface.docx](https://github.com/slaclab/amc-carrier-core/files/2228853/cryostat_card_interface.docx)
> Jmdewart cryo spi

- AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxCore.vhd
- AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxCoreCtrl.vhd
- AppHardware/AmcMicrowaveMux/xdc/AmcMicrowaveMuxBay0Pinout.xdc
- AppHardware/AmcMicrowaveMux/xdc/AmcMicrowaveMuxBay1Pinout.xdc
- python/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCore.py
- python/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCtrl.py
Added AmcMicrowaveMux's DAC JTAG ports
> Added AmcMicrowaveMux's DAC JTAG ports

- AmcCarrierCore/dcp/hdl/AmcCarrierCore.vhd
- AmcCarrierCore/dcp/hdl/AmcCarrierTiming.vhd
- ruckus.tcl
Remove references to ExptBusType.  Also, allow CORE_TRIGGERS_C=0.
> Remove references to ExptBusType.  Also, allow CORE_TRIGGERS_C=0.

- AmcCarrierCore/dcp/hdl/AmcCarrierRssiInterleave.vhd
- python/AppTop/TopLevel.py
- adding jumbo support to interleaved RSSI
[ESLCOMMON-228](https://jira.slac.stanford.edu/browse/ESLCOMMON-228)
> adding jumbo support to interleaved RSSI

- AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxCore.vhd
- AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxDualCore.vhd
driving LMK's CLKin0 with recovered timing clock
> driving LMK's CLKin0 with recovered timing clock

- AppHardware/RtmCryoDet/rtl/RtmCryoDet.vhd
- python/AppHardware/RtmCryoDet/_spiMax.py
- python/AppHardware/RtmCryoDet/_spiSr.py
Enable AxiSpiMaster SHADOW_EN_G
This caches SPI writes and returns cached value on axi lite read
Update pyrogue to make RtmCryoDet SPI RW
> Enable shadow memory for RtmCryoDet

- AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxCore.vhd
- AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxCoreCtrl.vhd
- python/AmcCarrierCore/AmcCarrierCore.py
- python/AppHardware/AmcCryo/_amcCryoCore.py
- python/AppHardware/AmcCryoDemo/_AmcCryoDemoCore.py
- python/AppHardware/AmcGenericAdcDac/_AmcGenericAdcDacCore.py
- python/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCore.py
- python/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCtrl.py
- python/AppTop/AppTop.py
- python/AppTop/TopLevel.py
- adding PC_379_396_30_C03 support
- updating writeBlocks() methods
> adding PC_379_396_30_C03 support

- AppHardware/RtmCryoDet/rtl/RtmCryoDacLut.vhd
- AppHardware/RtmCryoDet/rtl/RtmCryoDet.vhd
- AppHardware/RtmCryoDet/ruckus.tcl
- AppHardware/RtmCryoDet/tb/RtmCryoDacLutTb.vhd
- python/AppHardware/RtmCryoDet/__init__.py
- python/AppHardware/RtmCryoDet/_dacLut.py
- python/AppHardware/RtmCryoDet/_rtmCryoDet.py
-- Adding RtmCryoDacLut Module
> Adding RtmCryoDacLut Module

- AppHardware/AmcMrLlrfGen2UpConvert/core/AmcMrLlrfGen2UpConvertMapping.vhd
- AppHardware/AmcMrLlrfUpConvert/core/OutputTapDelay.vhd
- AppHardware/AmcMrLlrfUpConvert/v1/AmcMrLlrfUpConvertMapping.vhd
- AppHardware/AmcMrLlrfUpConvert/v2/AmcMrLlrfUpConvertMapping.vhd
- AppHardware/RtmCryoDet/rtl/RtmCryoDet.vhd
- AppHardware/RtmDigitalDebug/v1/RtmDigitalDebugV1.vhd
- AppHardware/RtmDigitalDebug/v2/RtmDigitalDebugDout.vhd
- AppHardware/RtmRfInterlock/v1/RtmRfInterlock.vhd
- AppHardware/RtmRfInterlock/v2/RtmRfInterlock.vhd
- AppHardware/common/rtl/JesdSyncOut.vhd
- adding SIM_DEVICE generic w.r.t. FpgaTypePkg
> adding SIM_DEVICE generic w.r.t. FpgaTypePkg

- AppHardware/RtmFastWireScanner/rtl/RtmFastWireScanner.vhd
Updated FWS RTM interface to include implementation details for both C00 and C01
> Fixing interface for FWS C00 and Adding C00 signals

- AppMps/rtl/AppMpsEncoder.vhd
In the previous version when mpsIgnore='1' the threshold processing was bypassed which resulted in the output message containing zeros, even if a threshold had been exceeded within the hold window.
This update fixes that so the mpsIgnore is processed in the threshold logic and the threshold hold still operates properly. 
I have also extended the threshold hold to 16 clocks.
This change also adds a hold function to the digital mode bits.
> Fix threshold memory to operate properly when mpsIgnore='1'

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- ruckus.tcl
- Updating to surf@v1.9.10 and ruckus@v1.7.8
>  v2.6.3 release candidate

- AppHardware/AmcMrLlrfDownConvert/core/AmcMrLlrfDownConvertCore.vhd
- AppHardware/AmcMrLlrfGen2UpConvert/core/AmcMrLlrfGen2UpConvert.vhd
- AppHardware/AmcMrLlrfUpConvert/core/AmcMrLlrfUpConvertCore.vhd
- updating AmcMrLlrf.I2C_DEVICE_MAP_C for repeated start
> updating AmcMrLlrf.I2C_DEVICE_MAP_C for repeated start

- AppHardware/RtmCryoDet/rtl/RtmCryoDetClkDiv.vhd
- AppHardware/RtmCryoDet/rtl/RtmCryoDetReg.vhd
- python/AppHardware/RtmCryoDet/_rtmCryoDet.py
RtmCryoDet add runtime configurable RTM clock deskew
> RtmCryoDet add runtime configurable RTM clock deskew

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/ip/SysMonCore.dcp
- AmcCarrierCore/ip/SysMonCore.xci
- AmcCarrierCore/non-fsbl/AmcCarrierRssiInterleave.vhd
- AppHardware/AmcMrLlrfDownConvert/core/AmcMrLlrfDownConvertCore.vhd
- AppHardware/AmcMrLlrfGen2UpConvert/core/AmcMrLlrfGen2UpConvert.vhd
- AppHardware/AmcMrLlrfUpConvert/core/AmcMrLlrfUpConvertCore.vhd
- AppHardware/RtmCryoDet/rtl/RtmCryoDetClkDiv.vhd
- AppHardware/RtmCryoDet/rtl/RtmCryoDetReg.vhd
- python/AppHardware/RtmCryoDet/_rtmCryoDet.py
- python/AppTop/TopLevel.py
- ruckus.tcl
- Updating to surf@v1.9.11
- updating AmcMrLlrf.I2C_DEVICE_MAP_C for repeated start #204
- RtmCryoDet add runtime configurable RTM clock deskew #205
> v2.6.4 release candidate

- AmcCarrierCore/non-fsbl/AmcCarrierRssi.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierRssiInterleave.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierRssiObFifo.vhd
- BsaCore/rtl/BsaWaveformEngine.vhd
- adding store/forward + choke to RSSI OB TSP
> adding store/forward + choke to RSSI OB TSP

- AmcCarrierCore/core/AmcCarrierTiming.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCoreAdv.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCoreBase.vhd
- python/AmcCarrierCore/AmcCarrierCore.py
- python/AmcCarrierCore/AmcCarrierTiming.py
- python/AppTop/TopLevel.py
Expose TimingCore USE_TPGMINI_G up to AmcCarrierCore.  Add enable flag to python.
> Add generic to disable TPG Mini

- AppHardware/AmcGenericAdcDac/rtl/AmcGenericAdcDacCore.vhd
- python/AppHardware/AmcGenericAdcDac/_AmcGenericAdcDacCtrl.py
- python/AppTop/AppTop.py
- python/AppTop/TopLevel.py
- AmcGenericAdcDac python updates based on regression testing with rogue v3.7.0
> AmcGenericAdcDac Python Updates

- AppHardware/AmcMrLlrfDownConvert/core/AmcMrLlrfDownConvertCore.vhd
- AppHardware/AmcMrLlrfUpConvert/v1/AmcMrLlrfUpConvertMapping.vhd
- AppHardware/AmcMrLlrfUpConvert/v2/AmcMrLlrfUpConvertMapping.vhd
- adding JesdSyncIn/Out to AppHardware/AmcMrLlrfUpConvert/ 
- adding JesdSyncIn/Out to AppHardware/AmcMrLlrfDownConvert/
> AppHardware/AmcMrLlrfUpConvert & AppHardware/AmcMrLlrfDownConvert Update

- AppHardware/AmcCryo/rtl/AmcCryoCore.vhd
- AppHardware/AmcCryoDemo/rtl/AmcCryoDemoCore.vhd
- adding JesdSyncIn/Out to AppHardware/AmcCryoDemo/
- adding JesdSyncIn/Out to AppHardware/AmcCryo/
> adding JesdSyncIn/Out to AppHardware/AmcCryoDemo/ and AppHardware/AmcCryo/

- AppHardware/AmcStriplineBpm/rtl/AmcStriplineBpmCore.vhd
- adding JesdSyncIn/Out to AppHardware/AmcStriplineBpm/
> adding JesdSyncIn/Out to AppHardware/AmcStriplineBpm/

- AmcCarrierCore/xdc/AmcCarrierCoreTiming.xdc
- AppTop/rtl/xcku040/AppTopJesd.vhd
- AppTop/rtl/xcku040_mpsln/AppTopJesd.vhd
- AppTop/rtl/xcku060/AppTopJesd.vhd
- AppTop/rtl/xcku11p/AppTopJesd.vhd
- AppTop/xdc/AppTop_gen1.xdc
- AppTop/xdc/AppTop_gen2.xdc
- switching the JESD clocks from MMCM to PLL
> switching the JESD clocks from MMCM to PLL

- python/AppTop/AppTop.py
PDN_SYSREF for ADC after JESD link established
> PDN_SYSREF for ADC after JESD link established

- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU040.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU060.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU095.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU11P.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU15P.vhd
- Updating the FpgaTypePkg.vhd to use correct CPSW_TARBALL_ADDR_C offset
> Updating FpgaTypePkg.vhd files

- AppMps/rtl/AppMpsPkg.vhd
This is original pull request I had under new branch. Please, merge it into pre-release.
> MPS L1 Update

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU040.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU060.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU095.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU11P.vhd
- AmcCarrierCore/core/FpgaType/FpgaTypePkg_XCKU15P.vhd
- AppHardware/AmcMrLlrfUpConvert/core/LvdsDacLane.vhd
- AppHardware/AmcMrLlrfUpConvert/v2/AmcMrLlrfUpConvertBay1Pinout.xdc
- AppHardware/RtmDigitalDebug/v2/RtmDigitalDebugV2.vhd
- AppMps/rtl/AppMpsPkg.vhd
- BsaCore/rtl/BldAxiStream.vhd
- Add BldAxiStream module from lcls-timing-core #237
- Fix for AxiDualPortRam generic interface change #238
- Updating FpgaTypePkg.vhd files #239
-  MPS L1 Update #240
> v2.7.1 release candidate

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- BsaCore/rtl/BsaBufferControl.vhd
- LICENSE.txt
- ruckus.tcl
- Update LICENSE.txt
- Update BsaBufferControl.vhd
- updating to latest surf
- MPS requires this for the bug fix for the boxcar filter/integrator
- https://github.com/slaclab/surf/pull/575
> v3.0.2 release candidate

- AmcCarrierCore/core/AmcCarrierSysReg.vhd
- python/AmcCarrierCore/AmcCarrierCore.py
- python/AppTop/TopLevel.py
- ruckus.tcl
- updating FW/SW from surf.AxiI2cRegMaster to surf.AxiLitePMbusMaster for PWR DC/DC
> updating FW/SW from surf.AxiI2cRegMaster to surf.AxiLitePMbusMaster for PWR DC/DC

- ruckus.tcl
- updating SURF lock to get bug fixes
> v3.1.1 release candidate

- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiMax.py
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiSr.py
https://jira.slac.stanford.edu/browse/ESLCOMMON-276
> Bug fix: Pass missing argument "name" to the base class

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/core/AmcCarrierSysRegPkg.vhd
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiMax.py
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiSr.py
- ruckus.tcl
- updating to surf@v2.1.3
- Bug fix: Pass missing argument "name" to the base class #259
> v3.1.5 release candidate

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- ruckus.tcl
> v3.2.0 release candidate

- python/AmcCarrierCore/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCore.py
- python/AmcCarrierCore/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCtrl.py
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiMax.py
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiSr.py
- python/AmcCarrierCore/AppTop/_AppTop.py
- AmcMicrowaveMuxCore: Enable ADC register verification
- Updated AmcMicrowaveMuxCore SYSREF sequence before load YAML into ADC devices
- adding retry to AppTop.Init()
> Resolving double YAML load issue

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/yaml/AmcCarrierTiming.yaml
- python/AmcCarrierCore/AppTop/_AppTop.py
- ruckus.tcl
- Update _AppTop.py #279
- Fix yaml for EvrV2TriggerReg with correct bit width for delay and pul… #278
- Changing surf to v2.6.1
> Release Candidate v3.5.1

- AmcCarrierCore/yaml/AmcCarrierTiming.yaml
- Update AmcCarrierTiming.yaml #281
> Release Candidate v3.5.2

- AppMps/rtl/AppMpsEncoder.vhd
- AppMps/rtl/AppMpsPkg.vhd
- AppMps/rtl/AppMpsSelect.vhd
Added update to handle additional MPS channels for LLRF and fix digital messages to diagnostic data 30 only. Version with modifications was only compiled
> Fixing digital MPS to diag word 30 only and adding channels to llrf app

- python/AmcCarrierCore/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCore.py
- Updates for deterministic latency startup reliability
> Another ESCRYODET-671 development Update #704

- python/AmcCarrierCore/AppHardware/AmcGenericAdcDac/_AmcGenericAdcDacCore.py
- python/AmcCarrierCore/AppTop/_AppTop.py
- updating AmcGenericAdcDacCore.py
- adding StatusValidCnt checking to AppTop.Init()
> Yet Another ESCRYODET-671 development Update

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- python/AmcCarrierCore/AppHardware/AmcGenericAdcDac/_AmcGenericAdcDacCore.py
- python/AmcCarrierCore/AppTop/_AppTop.py
- Yet Another ESCRYODET-671 development Update #295
> Release Candidate v3.5.9

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- python/AmcCarrierCore/AppHardware/AmcGenericAdcDac/_AmcGenericAdcDacCore.py
- python/AmcCarrierCore/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCore.py
- python/AmcCarrierCore/AppTop/_AppTop.py
- Yet Another ESCRYODET-671 development Update (DAC related) #297
> Release Candidate v3.5.10

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- python/AmcCarrierCore/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCore.py
- python/AmcCarrierCore/AppTop/_AppTop.py
- Yet Another ESCRYODET-671 development Update #302
>  Release Candidate v3.5.12

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- python/AmcCarrierCore/AppHardware/AmcMicrowaveMux/_amcMicrowaveMuxCore.py
- python/AmcCarrierCore/AppTop/_AppTop.py
- Yet Another ESCRYODET-671 development Update #304
> Release Candidate v3.5.13

- AppTop/xdc/AppTop_gen2.xdc
- Adding more timing margin for SMURF
- Related to ESCRYODET-671 and ESCRYODET-689
> AppTop/xdc/AppTop_gen2.xdc Update

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AppMps/rtl/AppMpsEncoder.vhd
- AppTop/xdc/AppTop_gen2.xdc
- bug fix for recent MPS LLRF update to 2-byte digital #306
- AppTop/xdc/AppTop_gen2.xdc Update #307
> Release Candidate v3.6.0

- AppHardware/RtmRfInterlock/core/RtmRfInterlockCore.vhd
- AppHardware/RtmRfInterlock/core/RtmRfInterlockFaultBuffer.vhd
- AppHardware/RtmRfInterlock/core/RtmRfInterlockReg.vhd
- AppHardware/RtmRfInterlock/v2/RtmRfInterlock.vhd
- AppHardware/RtmRfInterlock/yaml/RtmRfInterlock.yaml
Add fault history buffer for RTM ADCs.  Optionally send async message notifying SW of fault.
> LLRF RTM fault buffer

- AppHardware/RtmRfInterlock/core/RtmRfInterlockCore.vhd
- AppHardware/RtmRfInterlock/core/RtmRfInterlockFaultBuffer.vhd
Add valid strobe to fault buffer write address increment
> LLRF RTM ADC valid fix

- python/AmcCarrierCore/AppHardware/RtmCryoDet/_rtmCryoDet.py
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiMax.py
Will initialize all RTM DACs and set them to 0 as part of setDefaults
> Add InitRtm function that does CPLD reset and sets all DACs to 0

- python/AppHardware/AmcMrLlrfDownConvert/__init__.py
- python/AppHardware/AmcMrLlrfDownConvert/_amcMrLlrfDownConvert.py
- python/AppHardware/AmcMrLlrfGen2UpConvert/__init__.py
- python/AppHardware/AmcMrLlrfGen2UpConvert/_amcMrLlrfGen2UpConvert.py
- python/AppHardware/AmcMrLlrfUpConvert/__init__.py
- python/AppHardware/AmcMrLlrfUpConvert/_amcMrLlrfUpConvert.py
> Llrf python

- AppMps/rtl/AppMpsSalt.vhd
- AppMps/yaml/AppMpsSalt.yaml
- adding mpsPllLockCnt to AppMpsSalt.vhd
- adding MpsPllLockCnt to AppMpsSalt.yaml
> AppMpsSalt.vhd Update

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AppMps/rtl/AppMpsSalt.vhd
- AppMps/yaml/AppMpsSalt.yaml
- scripts/globalSubmoduleUpdate.py
> Release Candidate v4.3.1

- AppHardware/AmcMpsSfp/rtl/AmcMpsSfpMon.vhd
> Release Candidate v4.4.2

- AppMps/rtl/AppMpsPkg.vhd
Jeremy requested update in Cater 151369
>  Updating per cater 151369 to 8 thresholds

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AppMps/rtl/AppMpsPkg.vhd
- scripts/globalSubmoduleUpdate.py
> Release Candidate v4.4.3

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/core/kintexu/AmcCarrierEth.vhd
- AmcCarrierCore/core/kintexuplus/AmcCarrierEth.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCoreAdv.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCoreBase.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierRssi.vhd
- AppHardware/AmcMpsSfp/rtl/AmcMpsSfpMon.vhd
- scripts/globalSubmoduleUpdate.py
- always return AXI_RESP_OK_C for AmcMpsSfpMon
- adding DEBUG_PATH_SELECT_G generic
> Release Candidate v4.4.6

- AmcCarrierCore/core/AmcCarrierBsa.vhd
- AmcCarrierCore/yaml/AmcCarrierBsa.yaml
- BsaCore/rtl/BldAxiStream.vhd
- BsaCore/rtl/BldEventRAM.vhd
- BsaCore/rtl/BldEventSelect.vhd
- BsaCore/rtl/BldPkg.vhd
- BsaCore/rtl/BldWrapper.vhd
- BsaCore/rtl/BsssWrapper.vhd
- BsaCore/yaml/BldAxiStream.yaml
- Adds a rate-limited streaming option to the BLD stream for BSA scalars, per LCLS2 physics request. Needed for LCLS2 commissioning in February.
> Add BLD/BSSS streaming option

- AmcCarrierCore/core/AmcCarrierBsa.vhd
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/yaml/AmcCarrierBsa.yaml
- AppMps/rtl/AppMpsPkg.vhd
- BsaCore/rtl/BldAxiStream.vhd
- BsaCore/rtl/BldEventRAM.vhd
- BsaCore/rtl/BldEventSelect.vhd
- BsaCore/rtl/BldPkg.vhd
- BsaCore/rtl/BldWrapper.vhd
- BsaCore/rtl/BsssWrapper.vhd
- BsaCore/yaml/BldAxiStream.yaml
- ruckus.tcl
- #357
- LLRF application increase to 4 bytes (32-bits)
- updating submodule locks
> Release Candidate v4.5.0

- AmcCarrierCore/core/AmcCarrierBsa.vhd
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- BsaCore/rtl/BldAxiStream.vhd
- BsaCore/rtl/BldEventRAM.vhd
- BsaCore/rtl/BldEventSelect.vhd
- BsaCore/rtl/BldPkg.vhd
- BsaCore/rtl/BldWrapper.vhd
- BsaCore/rtl/BsssWrapper.vhd
- BsaCore/yaml/BldAxiStream.yaml
- bug fix when DISABLE_BSA_G=true and DISABLE_BLD_G=false
- whitespace removal
> Release Candidate v4.5.1

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/yaml/AmcCarrierBsa.yaml
> Release Candidate v4.5.2

- AmcCarrierCore/yaml/AmcCarrierBsa.yaml
- BsaCore/rtl/BldAxiStream.vhd
- BsaCore/rtl/BsaAccumulator.vhd
Fixes for BSSS/BLD service in BsaCore
> V4.5.2 severity

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/yaml/AmcCarrierBsa.yaml
- BsaCore/rtl/BldAxiStream.vhd
- BsaCore/rtl/BsaAccumulator.vhd
> Release Candidate v4.5.3

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- ruckus.tcl
- [updating submodule locks for MPS CN](https://github.com/slaclab/amc-carrier-core/commit/ac4d568a76f756dfbe9b197f525b1463e5cf5d80)
> Release Candidate v4.7.0

- AppMps/rtl/AppMpsEncoder.vhd
> Release Candidate v4.7.1

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AppMps/rtl/AppMpsPkg.vhd
> Release Candidate v4.7.2

- AmcCarrierCore/core/AmcCarrierBsa.vhd
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/yaml/AmcCarrierBsa.yaml
- BsaCore/rtl/BldAxiStream.vhd
- BsaCore/rtl/BsaBufferControl.vhd
- BsaCore/rtl/BsasAccumulator.vhd
- BsaCore/rtl/BsasModule.vhd
- BsaCore/rtl/BsasPkg.vhd
- BsaCore/rtl/BsasSampler.vhd
- BsaCore/rtl/BsasWrapper.vhd
- BsaCore/yaml/BldAxiStream.yaml
- BsaCore/yaml/BsaBufferControl.yaml
- BsaCore/yaml/BsasModule.yaml
- BsaCore/yaml/BsasStream.yaml
- BsaCore/yaml/BsasWrapper.yaml
- ruckus.tcl
> Release Candidate v4.8.0

- AmcCarrierCore/core/AmcCarrierBsa.vhd
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd
- AppMps/rtl/AppMpsPkg.vhd
- AppMps/rtl/AppMpsSelect.vhd
- AppTop/rtl/AppMsgOb.vhd
- AppTop/rtl/xcku040_mpsln/AppTopJesd.vhd
- BsaCore/rtl/BsasAccumulator.vhd
- BsaCore/rtl/BsasModule.vhd
- BsaCore/rtl/BsasPkg.vhd
- BsaCore/rtl/BsasSampler.vhd
- BsaCore/rtl/BsasWrapper.vhd
- DaqMuxV2/rtl/DaqRegItf.vhd
> Release Candidate v4.8.1

- BsaCore/rtl/BsasAccumulator.vhd
- Fix min/max calc in BsasAccumulator for cases of less than 1MHz accumulation
> BsaCore/rtl/BsasAccumulator.vhd Update

- BsaCore/rtl/BsasAccumulator.vhd
> Release Candidate v4.8.2

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiCryo.py
- python/AmcCarrierCore/AppTop/_AppTop.py
- python/AmcCarrierCore/AppTop/_AppTopJesd.py
- ruckus.tcl
- [resolved 'E275 missing whitespace after keyword' flake8 errors](https://github.com/slaclab/amc-carrier-core/commit/6ce48f3ef75e613c8e4fff1d6c90bb07addb3c26)
> Release Candidate v4.8.3

- AppMps/rtl/AppMpsEncoder.vhd
From Ryan
- Here is my proposed fix for the mps error Jeremy was seeing. The issue is there is logic to hold an mps threshold fault for 15uS to ensure it gets back tot he central node. This gets screwed up if they jump to a different threshold table, such as the idle table, and the threshold memory is not drained.
- Alternatively I could have just forced the other 7 threshold to be flushed when we go to the idle table, but this may be more future proof.
> MPS Mult thold fix

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AppMps/rtl/AppMpsEncoder.vhd
> Release Candidate v4.8.4

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AppMps/rtl/AppMpsPkg.vhd
> Release Candidate v4.8.5

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- DacSigGen/rtl/DacSigGen.vhd
- bug fix for MPS link node + DacSigGen
> Release Candidate v4.8.6

- .flake8
- AmcCarrierCore/core/AmcCarrierBsa.vhd
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/yaml/AmcCarrierBsa.yaml
- BsaCore/rtl/BldAxiStream.vhd
- BsaCore/rtl/BldWrapper.vhd
- BsaCore/rtl/BsaBufferControl.vhd
- BsaCore/rtl/BsssWrapper.vhd
- BsaCore/yaml/BsssWrapper.yaml
- ruckus.tcl
> Release Candidate v4.9.0

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- BsaCore/yaml/BsaBufferControl.yaml
> Release Candidate v4.9.2

- AppHardware/AmcMrLlrfDownConvert/core/AmcMrLlrfDownConvertCore.vhd
- AppHardware/AmcMrLlrfDownConvert/yaml/AmcMrLlrfDownConvert.yaml
- AppHardware/AmcMrLlrfGen2UpConvert/core/AmcMrLlrfGen2UpConvert.vhd
- AppHardware/AmcMrLlrfGen2UpConvert/yaml/AmcMrLlrfGen2UpConvert.yaml
- AppHardware/AmcMrLlrfUpConvert/core/AmcMrLlrfUpConvertCore.vhd
- AppHardware/AmcMrLlrfUpConvert/yaml/AmcMrLlrfUpConvert.yaml
- AppHardware/common/rtl/AmcClkFreqReg.vhd
- Adding this new register to upconverter and downconter at offset 0x000000A0
> adding AppHardware/common/rtl/AmcClkFreqReg.vhd

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- ruckus.tcl
- updating submodule locks for bug fixes in surf/ruckus
- https://github.com/slaclab/surf/pull/1051
- https://github.com/slaclab/surf/pull/1049
- https://github.com/slaclab/ruckus/pull/289
> Release Candidate v4.10.1

- .github/workflows/amc_ci.yml
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd
- AppHardware/AmcMicrowaveMux/rtl/hmc305.vhd
- AppHardware/RtmCryoDet/rtl/RtmCryoDet.vhd
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiCryo.py
- python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiMax.py
- ruckus.tcl
- updating submodule locks for bug fixes and enhancements 
- https://github.com/slaclab/lcls-timing-core/pull/157
- https://github.com/slaclab/surf/pull/1087
- https://github.com/slaclab/amc-carrier-core/pull/395
- https://github.com/slaclab/amc-carrier-core/pull/394
> Release Candidate v4.11.0

- python/AmcCarrierCore/BsaCore/_BsaBufferControl.py
- python/AmcCarrierCore/DacSigGen/_DacSigGen.py
Removes the use of MemoryDevice from AmcCarrierCore
> Remove use of MemoryDevice

- .github/workflows/amc_ci.yml
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- conda-recipe/meta.yaml
- python/AmcCarrierCore/BsaCore/_BsaBufferControl.py
- python/AmcCarrierCore/DacSigGen/_DacSigGen.py
- ruckus.tcl
- #398
- Fixed the CI anaconda release
- [updating lcls-timing-core to v3.7.7 to get a `Fix synthesis error with resize function` fix](https://github.com/slaclab/amc-carrier-core/commit/0bd5ed90f594a35aa3ea1b5dae7f4cbe5755b77e)
- [updating to latest surf at v2.45.1](https://github.com/slaclab/amc-carrier-core/commit/4c3ac1d37eaeade6844b4de76b08ac0edfd3e692)
> Release Candidate v4.11.1

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- ruckus.tcl
- updating to surf V2.45.2 to get bug fix for IDELAY
> Release Candidate v4.11.2

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/core/AmcCarrierSysReg.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCoreAdv.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCoreBase.vhd
- AppHardware/AmcMpsSfp/rtl/AmcMpsSfpCore.vhd
- AppHardware/AmcMpsSfp/rtl/AmcMpsSfpHsRepeater.vhd
- AppHardware/AmcMpsSfp/rtl/AmcMpsSfpMon.vhd
- python/AmcCarrierCore/AppHardware/AmcMpsSfp/_AmcMpsSfpCore.py
- python/AmcCarrierCore/AppHardware/AmcMpsSfp/_Ds125br401.py
- python/AmcCarrierCore/AppHardware/AmcMpsSfp/_SfpSummary.py
- python/AmcCarrierCore/AppHardware/AmcMpsSfp/__init__.py
- python/AmcCarrierCore/AppHardware/common/_Si5317a.py
- python/AmcCarrierCore/AppHardware/common/__init__.py
- ruckus.tcl
- [AmcMpsSfpCore.vhd: Code clean up](https://github.com/slaclab/amc-carrier-core/commit/977dfad82f710dc829c2763f597291b5456e13fe)
- [exposing AxiVersion.userReset to top-level](https://github.com/slaclab/amc-carrier-core/commit/cedca2146c93de9e8eaf866a89d732620efadfbe)
- [adding support to readout AmcMpsSfp.PCA9506](https://github.com/slaclab/amc-carrier-core/commit/d4f77343e97d18603db1b319a54bee12f6db9aa7)
- [adding AppHardware/AmcMpsSfp rogue SW](https://github.com/slaclab/amc-carrier-core/commit/e5af8626cc1686e95d25ed8251228f5ec60e4cd9)
- [updating surf/ruckus submodule locks](https://github.com/slaclab/amc-carrier-core/commit/636d9d583ca7c0860f87ebc009efaa8f83f7adac)
> Release Candidate v4.12.0

- AppHardware/AmcMpsSfp/yaml/Ds125br401.yaml
- python/AmcCarrierCore/AppHardware/AmcMpsSfp/_Ds125br401.py
- [Improve DS125br401 driver](https://github.com/slaclab/amc-carrier-core/commit/b34acda6afc675ab1081714c894f59e2731782cc)
> Ds125br401 driver

- AppHardware/AmcMpsSfp/yaml/AmcMpsSfpCore.yaml
- AppHardware/AmcMpsSfp/yaml/Ds125br401.yaml
- AppHardware/RtmDigitalDebug/v2b/RtmDigitalDebugV2b.vhd
- LICENSE.txt
- python/AmcCarrierCore/AppHardware/AmcMpsSfp/_Ds125br401.py
- python/AmcCarrierCore/AppHardware/RtmDigitalDebug/_RtmDigitalDebugV2b.py
- #402 
- #403
- [bug fixes for RtmDigitalDebugV2b](https://github.com/slaclab/amc-carrier-core/pull/404/commits/315b6b14b68ec3563bd6987c59a40c1b618910db)
> Release Candidate v4.12.1

- AmcCarrierCore/core/AmcCarrierBsa.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd
- BsaCore/rtl/BsaWaveformEngine.vhd
This allows the option to optimize away the waveform engine.
> Add options to specify WAVEFORM_NUMLANES_G=0

- AmcCarrierCore/core/AmcCarrierBsa.vhd
- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AmcCarrierCore/core/kintexu/AmcCarrierEth.vhd
- AmcCarrierCore/core/kintexuplus/AmcCarrierEth.vhd
- AmcCarrierCore/fsbl/kintexu/AmcCarrierEthFsbl.vhd
- AmcCarrierCore/fsbl/kintexuplus/AmcCarrierEthFsbl.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCoreAdv.vhd
- AmcCarrierCore/non-fsbl/AmcCarrierCoreBase.vhd
- AppTop/rtl/xcku040/AppTop.vhd
- AppTop/rtl/xcku060/AppTop.vhd
- BsaCore/rtl/BsaWaveformEngine.vhd
- ruckus.tcl
- #409
-  [updating submodule lock to ruckus@4.16.2](https://github.com/slaclab/amc-carrier-core/commit/3776a79532b29c5d8338fca54bf4e6bb1c4e6d9c)
- [updating code for surf v2.50.0 forward compatiblity](https://github.com/slaclab/amc-carrier-core/commit/7b708b179805522e45529ee6193dd837e166c5d7)
- [whitespace removal](https://github.com/slaclab/amc-carrier-core/pull/410/commits/49fdcc9aea04f7391b259a692628a4b8ba030324)
- [emacs VHDL beautify](https://github.com/slaclab/amc-carrier-core/pull/410/commits/78b9460818b1326037c17955f11db89dcdb04fa6)
> Release Candidate v5.1.1

- AmcCarrierCore/core/AmcCarrierPkg.vhd
- AppMps/rtl/AppMpsClk.vhd
- LICENSE.txt
- ruckus.tcl
- [Update AppMpsClk.vhd - fixed typo](https://github.com/slaclab/amc-carrier-core/commit/ea2375d6e9af0df2bf1517a3031921dfac03e384)
- [Update LICENSE.txt](https://github.com/slaclab/amc-carrier-core/commit/db72840b054f1bb6d466aa675b0ff65f7ed31f7f)
- [upgrading to latest submodule releases](https://github.com/slaclab/amc-carrier-core/pull/413/commits/af7775eb896998e8d2e55bc244aa226dc6bcf4a2)
- https://github.com/slaclab/lcls-timing-core/pull/180
- https://github.com/slaclab/lcls-timing-core/pull/176
- https://github.com/slaclab/lcls-timing-core/pull/164 
- https://github.com/slaclab/surf/pull/1153 
- https://github.com/slaclab/surf/pull/1149
> Release Candidate v5.2.0
