AppTop/rtl/xcku040/AppTop.vhd, AppTop/rtl/xcku040_mpsln/AppTop.vhd, AppTop/rtl/xcku060/AppTop.vhd, AppTop/rtl/xcku11p/AppTop.vhd
The debug stream outbound from AppCore was connected to an intermediate signal which was otherwise unconnected thus rendering the outbound debug stream non-functional.
=> AppTop fails to connect outbound debug stream

AmcCarrierCore/dcp/hdl/AmcCarrierTiming.vhd
The fix uses a combinatorial process to make sure all not explicitly
altered members of the TimingBusType record are propagated. This
ensures compatibility with possible future additions...
=> FIX for ESLCOMMON-225 (AmcCarrierTiming fails to propagate TimingBusType.modesel)

.lfsconfig
A while ago an '.lfsconfig' file was erroneously pushed. This was meant for local use only.
=> ESLCOMMON-234

python/AppTop/TopLevel.py
- updating to new 256 indpedent TDEST/DMA driver
- Requires [surf@v1.9.4](https://github.com/slaclab/surf/tree/v1.9.4) (or later)
- Requires [aes-stream-drivers@v5.2.0](https://github.com/slaclab/aes-stream-drivers/releases/tag/v5.2.0) (or later)
- Requires [rogue@v3.0.2](https://github.com/slaclab/rogue/releases/tag/v3.0.2) (or later)
=> updating to new 256 indpedent TDEST/DMA driver

AppMps/rtl/AppMpsPkg.vhd
APP_MPS_6CH_TYPE_C uses index 0-5
=> Fix channel mapping:

AppHardware/AmcMicrowaveMux/rtl/hmc305.vhd, python/AppHardware/AmcMicrowaveMux/_hmc305.py
Fix shadow register for hmc305, should hold 8 values.  
Update pyrogue registers RW  to match the shadow registers.
=> Fix shadow register for hmc305, should hold 8 values.  

AppHardware/AmcMicrowaveMux/rtl/hmc305.vhd
Update REG_INIT_C data to match hardware bootup - attenuators power up at 0x1F.  This fixes inconsistency with readback after power up.
=> Update HMC305 bootup values

BsaCore/rtl/BsaWaveformEngine.vhd
Preventing 10 GbE link saturation
=> Limitting the waveform dumps to 5Gb/s to prevent

AmcCarrierCore/core/AmcCarrierBsa.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCoreAdv.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCoreBase.vhd, AppTop/rtl/xcku11p/AppTop.vhd, BsaCore/rtl/BsaWaveformEngine.vhd, DaqMuxV2/rtl/DaqRegItf.vhd, python/AmcCarrierCore/AmcCarrierBsa.py, python/AmcCarrierCore/AmcCarrierCore.py, python/AppTop/AppTop.py, python/AppTop/TopLevel.py, python/BsaCore/BsaWaveformEngine.py, python/DaqMuxV2/DaqMuxV2.py
- Default of WAVEFORM_NUM_LANES_G=4
- To implement in FW, you must set WAVEFORM_NUM_LANES_G for both AppTop.vhd and AmcCarrierCoreAdv.vhd to be the same
- To implement in SW, you must set TopLevel.py's numWaveformBuffers to be the same as FWWAVEFORM_NUM_LANES_G
=> Adding WAVEFORM_NUM_LANES_G support

AppHardware/AmcGenericAdcDac/rtl/AmcGenericAdcDacCore.vhd
Resolve the following error messages in Vivado when smaTrig or adcCal is not statically drive:
```
[Synth 8-1565] actual for formal port smatrig is neither a static name nor a globally static expression ["/firmware/submodules/amc-carrier-core/AppHardware/AmcGenericAdcDac/rtl/AmcGenericAdcDacCore.vhd":472] 
[Synth 8-1565] actual for formal port smatrig is neither a static name nor a globally static expression ["/firmware/submodules/amc-carrier-core/AppHardware/AmcGenericAdcDac/rtl/AmcGenericAdcDacCore.vhd":473]
```
=> AmcGenericAdcDacCore-update

AppHardware/AmcCryo/rtl/AmcCryoCore.vhd, AppHardware/AmcCryo/rtl/AmcCryoDualCore.vhd, AppHardware/AmcCryoDemo/rtl/AmcCryoDemoCore.vhd, AppHardware/AmcCryoDemo/rtl/AmcCryoDemoDualCore.vhd, AppHardware/AmcGenericAdcDac/rtl/AmcGenericAdcDacCore.vhd, AppHardware/AmcGenericAdcDac/rtl/AmcGenericAdcDacDualCore.vhd, AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxCore.vhd, AppHardware/AmcMicrowaveMux/rtl/AmcMicrowaveMuxDualCore.vhd, AppHardware/AmcMrLlrfGen2UpConvert/core/AmcMrLlrfGen2UpConvert.vhd, AppHardware/AmcMrLlrfGen2UpConvert/core/AmcMrLlrfGen2UpConvertMapping.vhd, AppTop/rtl/xcku040/AppTop.vhd, AppTop/rtl/xcku040/AppTopJesd.vhd, AppTop/rtl/xcku040/AppTopJesd204b.vhd, AppTop/rtl/xcku040_mpsln/AppTop.vhd, AppTop/rtl/xcku040_mpsln/AppTopJesd.vhd, AppTop/rtl/xcku040_mpsln/AppTopJesd204b.vhd, AppTop/rtl/xcku060/AppTop.vhd, AppTop/rtl/xcku060/AppTopJesd.vhd, AppTop/rtl/xcku060/AppTopJesd204b.vhd, AppTop/rtl/xcku11p/AppTop.vhd, AppTop/rtl/xcku11p/AppTopJesd.vhd, AppTop/rtl/xcku11p/AppTopJesd204b.vhd
- adding multiple JesdTx sync support
- used for multiple DAC ICs with different SYNCs
- Addresses the issue in JIRA [ESCRYODET-401](https://jira.slac.stanford.edu/browse/ESCRYODET-401)
- This will break existing builds and require them to map each SYNC with respect to each TX JESD lane
=> adding multiple JesdTx sync support

python/AppTop/AppCore.py, python/AppTop/AppTop.py, python/AppTop/TopLevel.py, python/AppTop/__init__.py
Instead of relying on an external python package called "common" this new method will rely on the developer adding an object which is a sub-class of AppTop.AppCore to the device tree from a higher level python script.
`````
class MyAppCore(AppTop.AppCore):
....
self.FpgaTopLevel.AppTop.add(MyAppCore(name='blah'))
`````
=> New method for adding AppCore devices to AppTop device

AmcCarrierCore/core/AmcCarrierPkg.vhd, AppMps/rtl/AppMpsEncoder.vhd, AppMps/rtl/AppMpsPkg.vhd, AppMps/rtl/AppMpsRegBase.vhd, AppMps/yaml/AppMpsRegBase.yaml
This PR does the following.
1. Add MPS support for the fast wire scanner.
2. Remove the different link node types and replace with link node and application node types.
3. Allow LCLS1 and LCLS2 modes to generate different size MPS messages.
=> Change app types and allow different mps message size for lcls1

AppHardware/AmcMrLlrfUpConvert/core/LvdsDacLane.vhd, AppHardware/AmcMrLlrfUpConvert/v2/AmcMrLlrfUpConvertBay1Pinout.xdc, AppHardware/RtmDigitalDebug/v2/RtmDigitalDebugV2.vhd
MrLlrfUpConvert never migrated to match surf change in AxiDualPortRam generics change.
=> Fix for AxiDualPortRam generic interface change

AmcCarrierCore/core/AmcCarrierPkg.vhd, ruckus.tcl
- updating to submodule lock to surf@v2.1.2
- https://github.com/slaclab/surf/pull/635
- Latest tag release before migrating to lcls-timing-core version3
=> v3.1.4 release candidate

ruckus.tcl
- Updated to supported "2018.3 2019.1 2019.2 2020.1"
=> Updating Vivado Version locks

AppMps/rtl/AppMpsPkg.vhd
Per Jeremy request increased number thresholds to 8 for BCM/BLEN systems
=> Increasing to 8 number of MPS thresholds for BCM and BLEN

AppMps/rtl/AppMpsSalt.vhd, AppMps/yaml/AppMpsSalt.yaml
- adding mpsChEnable bitmask to AppMpsSalt.vhd
- updating AppMpsSalt.yaml with MpsChEnable reg
=> Update to AppMpsSalt.vhd for masking off unused RX SALT channels on the ATCA backplane

AmcCarrierCore/core/AmcCarrierPkg.vhd
We need to have DN (digital) link node ID to support it
=> Reentering missing DN application ID 122

AmcCarrierCore/core/kintexu/AmcCarrierEth.vhd, AmcCarrierCore/core/kintexuplus/AmcCarrierEth.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd, BsaCore/rtl/BsaAccumulator.vhd
- RSSI interleaved mode is not used in LCLS-II applciation
- This means that it is an "unused" UDP port 
- SMURF SO is the only application that uses this RSSI interleaved mode (non-LCLS-II application)
- This pull request keeps the UDP port 8197 (tprPattern) the same
- But moves the bldDriver & bsssDriver to UDP port 8198 
- This changed was proposed to Kukhee during a meeting with him.  
- This PR is intended to communicate the changes to Matt Weaver.
=> Repurposing the LCLS-II unused 8198 UDP port for BLD/BSSS

.flake8, AmcCarrierCore/core/AmcCarrierBsa.vhd, AmcCarrierCore/core/AmcCarrierPkg.vhd, AmcCarrierCore/yaml/AmcCarrierBsa.yaml, BsaCore/rtl/BldAxiStream.vhd, BsaCore/rtl/BldWrapper.vhd, BsaCore/rtl/BsaBufferControl.vhd, BsaCore/rtl/BsssWrapper.vhd, BsaCore/yaml/BsssWrapper.yaml, ruckus.tcl
- Expands BSSS coverage to all BSA buffers except the top 4 (MPS fault history).  Reduces BSA buffer allocation from 64 to 48.
- [flake8 Version 6 fixes](https://github.com/slaclab/amc-carrier-core/pull/385/commits/2e02cb9a628d775b739746d776fe10c7678466f4)
=> V4.8.3 bsa bsss reallocation

AmcCarrierCore/core/AmcCarrierBsa.vhd, AmcCarrierCore/core/AmcCarrierBsi.vhd, AmcCarrierCore/yaml/AmcCarrierBsa.yaml, BsaCore/rtl/BsaBufferControl.vhd, BsaCore/rtl/BsssWrapper.vhd, BsaCore/yaml/BsssWrapper.yaml
Fixes to v4.9.0 for the dma end addr misalignment, the svcTs bit for BSSS rate limits, and the number of EDEFs for BSAS.
=> V4.9.0 bsafixes

AmcCarrierCore/core/AmcCarrierBsa.vhd, AmcCarrierCore/core/AmcCarrierBsi.vhd, AmcCarrierCore/core/AmcCarrierPkg.vhd, AmcCarrierCore/yaml/AmcCarrierBsa.yaml, BsaCore/rtl/BsaBufferControl.vhd, BsaCore/rtl/BsssWrapper.vhd, BsaCore/yaml/BsssWrapper.yaml
- [Fixes to v4.9.0 for the dma end addr misalignment, the svcTs bit for BSSS rate limits, and the number of EDEFs for BSAS.](https://github.com/slaclab/amc-carrier-core/pull/387)
=> Release Candidate v4.9.1

python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiMax.py
- Default of 0x2 for DacCtrlRegCh registers keeps precision SMuRF slow DACs from railing negative during setDefaults.  See ESCRYODET-924 for more details.
=> Updating python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiMax.py

AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd, AppHardware/AmcMicrowaveMux/rtl/hmc305.vhd, AppHardware/RtmCryoDet/rtl/RtmCryoDet.vhd, python/AmcCarrierCore/AppHardware/RtmCryoDet/_spiCryo.py
- Allow the CryoDet RTM `LEMO_IN` signal to pass directly to the application firmware. It is also still used for the ramp stuff, but this could maybe be deleted.
- Fix an incorrect assert statement to allow interleaved RSSI that was introduced in #364.
- Clean up VHDL syntax for xsim simulation.
- Remove unfinished cryocard readback and control from rogue code.
=> RtmCryoDet - Pass LEMO_IN to application

AmcCarrierCore/core/AmcCarrierPkg.vhd, AppTop/rtl/xcku040/AppTop.vhd, AppTop/rtl/xcku060/AppTop.vhd, AppTop/ruckus.tcl, ruckus.tcl
- https://github.com/slaclab/amc-carrier-core/pull/405 is `API BREAKING` change:
- Requires that the AppCore adds `appTimingClk`  and `appTimingRst` 
- This option to use application supplied clock from AppCore for timing.  
- [example of how to update your AppCore.vhd for amc-carrier-core@v5.0.0](https://github.com/slaclab/amc-carrier-project-template/commit/a03a777f714c1efb5749627ea146c35eee393a7a)
- Add build option to use KCU040 modules with KCU060 FPGA target.
=> Release Candidate v5.0.0

AmcCarrierCore/fsbl/AmcCarrierCoreFsbl.vhd, AmcCarrierCore/fsbl/AmcCarrierFsbl.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCoreAdv.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCoreBase.vhd, AppMps/rtl/AppMps.vhd, AppMps/rtl/AppMpsClk.vhd
- Creating a 125 MHz on the same PLL as AXI-Lite to reduce the number of cascaded PLLs to make this clock
- Using the external 125 MHz clock reference (instead of internal) to make the clocking identical between linkNode and appNode in MPS's 125MHz, 156.25MHz and 625 MHz clock generation.
=> reorg of the ref125MHzClk used for linkNode and appNode

.github/workflows/amc_ci.yml, AmcCarrierCore/core/AmcCarrierPkg.vhd, AmcCarrierCore/core/kintexuplus/AmcCarrierEth.vhd, AmcCarrierCore/fsbl/AmcCarrierCoreFsbl.vhd, AmcCarrierCore/fsbl/AmcCarrierFsbl.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCore.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCoreAdv.vhd, AmcCarrierCore/non-fsbl/AmcCarrierCoreBase.vhd, AppMps/rtl/AppMps.vhd, AppMps/rtl/AppMpsClk.vhd, BsaCore/ruckus.tcl, ruckus.tcl
- [reorg of the ref125MHzClk used for linkNode and appNode](https://github.com/slaclab/amc-carrier-core/commit/566ee92cd64eae18a38ace954a22006f5a8c3c77)
- [adding optional output ports required for RFMC carrier](https://github.com/slaclab/amc-carrier-core/commit/05ad7290e00bc8c625543275ae785acbdae05453)
- [adding zynquplusRFSOC support to BSA ruckus.tcl](https://github.com/slaclab/amc-carrier-core/commit/4189f6a4005b124e7f17f3409d1d9ea18c7f14ee)
- [migrating CI from ubuntu-20.04 to ubuntu-24.04](https://github.com/slaclab/amc-carrier-core/commit/8b5e1befcacde6cf06af945dde2374bfe686e7a6)
=> Release Candidate v5.3.0
